# git-cliff configuration for release changelog
# Docs: https://github.com/orhun/git-cliff

[changelog]
header = ""
body = "{{#each groups}}{{#if commits}}\n### {{title}}\n{{#each commits}}- {{this.message | trim}} ({{this.sha}})\n{{/each}}{{/if}}{{/each}}\n"
footer = ""
trim = true

[git]
conventional_commits = true
filter_unconventional = true

commit_parsers = [
  { message = "feat\(.*\):", group = "Features" },
  { message = "fix\(.*\):", group = "Bug Fixes" },
  { message = "perf\(.*\):", group = "Performance" },
  { message = "refactor\(.*\):", group = "Refactors" },
  { message = "docs\(.*\):", group = "Documentation" },
  { message = "chore\(.*\):", group = "Chores" },
  { message = "test\(.*\):", group = "Tests" },
  { message = "ci\(.*\):", group = "CI" }
]

protect_breaking_changes = true
